import { describe, expect, it } from "vitest";
import { createImporterContext } from "../../../src/core/config/context";
import { parseKontenConfig } from "../../../src/core/config/konten";
import { txHash } from "../../../src/core/import/dedupe";
import {
	CLEARING_ACCOUNT,
	categorizeAll,
	fmtEur,
	formatAccounts,
	formatJournal,
	formatTransaction,
	routeSelfTransfersViaClearing,
	type CategorizedTx,
} from "../../../src/core/import/journal";
import { deriveOwnerNames } from "../../../src/core/import/categorize";
import { EMPTY_RULES } from "../../../src/core/import/rules";
import { Money } from "../../../src/core/money";
import { makeTx } from "./factory";

const ctx = createImporterContext({
	notesPrefix: "Finanzplan",
	konten: parseKontenConfig({
		konten: [
			{
				id: "haupt",
				iban: "DE1",
				ledger_account: "Aktiva:Bank:Hauptkonto",
				bank: "Sparkasse",
				konto_typ: "giro",
				konto_rolle: "hauptkonto_privat",
				csv_schema: "sparkasse_camt52",
				inhaber: "Max Mustermann",
			},
			{
				id: "vermietung",
				iban: "DE2",
				ledger_account: "Aktiva:Bank:Vermietung",
				bank: "Sparkasse",
				konto_typ: "giro",
				konto_rolle: "vermietung",
				csv_schema: "sparkasse_camt52",
				inhaber: "Max Mustermann",
			},
		],
	}),
});

describe("fmtEur", () => {
	it("schreibt Punkt-Notation mit Währung", () => {
		expect(fmtEur(new Money("-39.95"))).toBe("-39.95 EUR");
		expect(fmtEur(new Money("1307.6"))).toBe("1307.60 EUR");
		expect(fmtEur(new Money("0"))).toBe("0.00 EUR");
	});
});

describe("formatTransaction", () => {
	it("schreibt den vollständigen hledger-Block", () => {
		const block = formatTransaction(
			makeTx({
				buchungstag: "2025-08-01",
				beguenstigter: "Telekom Deutschland GmbH",
				verwendungszweck: "Festnetz Vertragskonto 123",
				betrag: new Money("-39.95"),
				quelle: "auszug.CSV",
				rawRowIdx: 12,
			}),
			"Aktiva:Bank:Hauptkonto",
			"Ausgaben:Kommunikation:Festnetz:Telekom",
			["recurring"],
		);
		expect(block).toBe(
			[
				"2025-08-01 * Telekom Deutschland GmbH",
				"    ; verwendungszweck: Festnetz Vertragskonto 123",
				"    ; quelle: auszug.CSV row 12",
				"    ; :recurring:",
				"    Aktiva:Bank:Hauptkonto  -39.95 EUR",
				"    Ausgaben:Kommunikation:Festnetz:Telekom  39.95 EUR",
				"",
			].join("\n"),
		);
	});

	it("lässt Verwendungszweck und Tag-Zeile weg, wenn es nichts zu schreiben gibt", () => {
		const block = formatTransaction(
			makeTx({ verwendungszweck: "" }),
			"A",
			"B",
			[],
		);
		expect(block).not.toContain("verwendungszweck");
		expect(block).not.toMatch(/; :/);
	});

	it("schreibt mehrere Tags auf eine Zeile", () => {
		expect(
			formatTransaction(makeTx(), "A", "B", ["recurring", "paypal-via"]),
		).toContain("    ; :recurring:paypal-via:");
	});

	it("legt umbrochene Verwendungszwecke auf eine Zeile", () => {
		const block = formatTransaction(
			makeTx({ verwendungszweck: "Zeile eins\nZeile   zwei" }),
			"A",
			"B",
			[],
		);
		expect(block).toContain("; verwendungszweck: Zeile eins Zeile zwei");
	});

	it("fällt für die Beschreibung auf Buchungstext und Platzhalter zurück", () => {
		expect(
			formatTransaction(
				makeTx({ beguenstigter: "", buchungstext: "ENTGELTABSCHLUSS" }),
				"A",
				"B",
				[],
			),
		).toContain("2025-08-01 * ENTGELTABSCHLUSS");
		expect(
			formatTransaction(
				makeTx({ beguenstigter: "", buchungstext: "" }),
				"A",
				"B",
				[],
			),
		).toContain("2025-08-01 * (unbekannt)");
	});
});

describe("formatJournal", () => {
	const item = (
		buchungstag: string,
		quelle: string,
		rawRowIdx: number,
	): CategorizedTx => ({
		tx: makeTx({ buchungstag, quelle, rawRowIdx, beguenstigter: `${quelle}#${rawRowIdx}` }),
		posting: "A",
		result: { gegenAccount: "B", tags: [], ruleName: "x" },
	});

	it("sortiert nach Datum, dann Quelldatei, dann Zeilennummer", () => {
		const journal = formatJournal([
			item("2025-08-02", "b.CSV", 1),
			item("2025-08-01", "b.CSV", 2),
			item("2025-08-01", "a.CSV", 9),
			item("2025-08-01", "b.CSV", 1),
		]);
		const order = [...journal.matchAll(/\* (\S+#\d+)/g)].map((m) => m[1]);
		expect(order).toEqual(["a.CSV#9", "b.CSV#1", "b.CSV#2", "b.CSV#1"]);
	});

	it("schreibt den Kopf auch ohne Buchungen", () => {
		expect(formatJournal([])).toContain("; Generated by finanzplan-importer");
	});
});

describe("formatAccounts", () => {
	it("deklariert die konfigurierten Konten und die der Regeln", () => {
		const accounts = formatAccounts(
			ctx,
			{
				counterparty: [
					{ pattern: "x", ledgerAccount: "Ausgaben:Neu:Konto", tags: [] },
				],
				paypal: [],
			},
			["Einnahmen:Sonderregel"],
		);
		expect(accounts).toContain("account Aktiva:Bank:Hauptkonto");
		expect(accounts).toContain("account Aktiva:Bank:Vermietung");
		expect(accounts).toContain("account Ausgaben:Neu:Konto");
		expect(accounts).toContain("account Einnahmen:Sonderregel");
		expect(accounts).toContain(`account ${CLEARING_ACCOUNT}`);
	});

	it("nennt jedes Konto genau einmal und sortiert", () => {
		const lines = formatAccounts(ctx, EMPTY_RULES)
			.split("\n")
			.filter((l) => l.startsWith("account "));
		expect(new Set(lines).size).toBe(lines.length);
		expect([...lines].sort()).toEqual(lines);
	});
});

describe("routeSelfTransfersViaClearing", () => {
	const selfTransfer = (gegenAccount: string): CategorizedTx => ({
		tx: makeTx(),
		posting: "Aktiva:Bank:Hauptkonto",
		result: { gegenAccount, tags: ["self-transfer"], ruleName: "self-transfer-eigen" },
	});

	it("leitet eine Umbuchung zwischen importierten Konten übers Verrechnungskonto", () => {
		const [item] = routeSelfTransfersViaClearing(
			[selfTransfer("Aktiva:Bank:Vermietung")],
			ctx.importedLedgerAccounts,
		);
		expect(item.result.gegenAccount).toBe(CLEARING_ACCOUNT);
	});

	// Der Defekt vom 2026-08-01: greift die Umleitung zu breit, bekommt das
	// Zielkonto seine Bewegung nie und im Durchlaufkonto bleibt der Betrag liegen.
	it("bucht direkt aufs Ziel, wenn die Gegenseite keine eigene CSV liefert", () => {
		const [item] = routeSelfTransfersViaClearing(
			[selfTransfer("Aktiva:Bank:Bauspar")],
			ctx.importedLedgerAccounts,
		);
		expect(item.result.gegenAccount).toBe("Aktiva:Bank:Bauspar");
	});

	it("lässt normale Ausgaben unangetastet", () => {
		const normal: CategorizedTx = {
			tx: makeTx(),
			posting: "Aktiva:Bank:Hauptkonto",
			result: { gegenAccount: "Ausgaben:Essen", tags: ["recurring"], ruleName: "x" },
		};
		expect(
			routeSelfTransfersViaClearing([normal], ctx.importedLedgerAccounts)[0].result
				.gegenAccount,
		).toBe("Ausgaben:Essen");
	});

	it("hebt beide Seiten einer Umbuchung im Verrechnungskonto auf", () => {
		// Dieselbe Umbuchung, wie sie in beiden Auszügen steht: einmal Abgang beim
		// Hauptkonto, einmal Eingang beim Zielkonto.
		const abgang = makeTx({
			accountIban: "DE1",
			beguenstigter: "Max Mustermann",
			kontonummerIban: "DE2",
			betrag: new Money("-150.00"),
		});
		const eingang = makeTx({
			accountIban: "DE2",
			beguenstigter: "Max Mustermann",
			kontonummerIban: "DE1",
			betrag: new Money("150.00"),
		});
		const categorized = categorizeAll([abgang, eingang], {
			ctx,
			rules: EMPTY_RULES,
			ownerNames: deriveOwnerNames(ctx),
			signRules: [],
		});

		expect(categorized.every((c) => c.result.gegenAccount === CLEARING_ACCOUNT)).toBe(
			true,
		);
		// Jedes Konto bewegt sich genau um seinen eigenen Betrag …
		expect(categorized[0].posting).toBe("Aktiva:Bank:Hauptkonto");
		expect(categorized[1].posting).toBe("Aktiva:Bank:Vermietung");
		// … und im Durchlaufkonto heben sich beide Seiten auf.
		const clearingSum = categorized.reduce(
			(sum, c) => sum.plus(c.tx.betrag.negated()),
			new Money(0),
		);
		expect(clearingSum.toFixed(2)).toBe("0.00");
	});
});

describe("txHash", () => {
	it("nutzt die Sammlerreferenz, wenn sie vorhanden ist", () => {
		const a = makeTx({ sammlerreferenz: "SREF-1", betrag: new Money("-1.00") });
		const b = makeTx({ sammlerreferenz: "SREF-1", betrag: new Money("-999.00") });
		// Gleiche Bank-Transaktions-ID heißt gleiche Buchung, egal was sonst variiert.
		expect(txHash(a)).toBe(txHash(b));
	});

	it("ignoriert Leerraum um die Sammlerreferenz", () => {
		expect(txHash(makeTx({ sammlerreferenz: " SREF-1 " }))).toBe(
			txHash(makeTx({ sammlerreferenz: "SREF-1" })),
		);
	});

	it("unterscheidet ohne Sammlerreferenz über Konto, Tag, Betrag und Zweck", () => {
		const base = makeTx({ verwendungszweck: "Miete August" });
		expect(txHash(base)).not.toBe(txHash(makeTx({ accountIban: "DE9" })));
		expect(txHash(base)).not.toBe(txHash({ ...base, buchungstag: "2025-08-02" }));
		expect(txHash(base)).not.toBe(
			txHash({ ...base, betrag: new Money("-10.01") }),
		);
		expect(txHash(base)).not.toBe(
			txHash({ ...base, verwendungszweck: "Miete September" }),
		);
	});

	it("ist unempfindlich gegen Groß-/Kleinschreibung im Verwendungszweck", () => {
		expect(txHash(makeTx({ verwendungszweck: "MIETE" }))).toBe(
			txHash(makeTx({ verwendungszweck: "miete" })),
		);
	});

	it("sieht nur die ersten 60 Zeichen des Verwendungszwecks", () => {
		const prefix = "x".repeat(60);
		expect(txHash(makeTx({ verwendungszweck: `${prefix}AAA` }))).toBe(
			txHash(makeTx({ verwendungszweck: `${prefix}BBB` })),
		);
	});

	it("liefert einen 16-stelligen Hex-Wert", () => {
		expect(txHash(makeTx())).toMatch(/^[0-9a-f]{16}$/);
	});
});
