import { describe, expect, it } from "vitest";
import { createImporterContext } from "../../../src/core/config/context";
import { parseKontenConfig } from "../../../src/core/config/konten";
import {
	formatOpeningBalances,
	parseAnfangssaldo,
	parseStandAm,
	readAnfangssaldo,
} from "../../../src/core/import/openingBalances";

function konto(overrides: Record<string, unknown> = {}) {
	return {
		id: "hauptkonto",
		iban: "DE1",
		ledger_account: "Aktiva:Bank:Sparkasse:Hauptkonto",
		bank: "Sparkasse Musterstadt",
		konto_typ: "giro",
		konto_rolle: "hauptkonto",
		csv_schema: "camt52",
		inhaber: "Max Mustermann",
		filename: "Konto 01 – Hauptkonto.md",
		...overrides,
	};
}

const ctx = createImporterContext({
	konten: parseKontenConfig({ konten: [konto()] }),
	notesPrefix: "Finanzplan",
});

describe("parseAnfangssaldo", () => {
	it("liest die deutsche Schreibweise aus Obsidians Eigenschaften-Editor", () => {
		expect(parseAnfangssaldo("443,72").toString()).toBe("443.72");
		expect(parseAnfangssaldo("-340,51").toString()).toBe("-340.51");
	});

	it("liest deutsche Tausendertrenner", () => {
		expect(parseAnfangssaldo("1.234,56").toString()).toBe("1234.56");
	});

	it("liest die Punkt-Schreibweise, die YAML selbst erzeugt", () => {
		expect(parseAnfangssaldo("443.72").toString()).toBe("443.72");
		expect(parseAnfangssaldo(443.72).toString()).toBe("443.72");
		expect(parseAnfangssaldo(0).toString()).toBe("0");
	});

	it("wirft bei etwas, das keine Zahl ist", () => {
		expect(() => parseAnfangssaldo("k.A.")).toThrow();
	});
});

describe("parseStandAm", () => {
	it("nimmt ISO unverändert", () => {
		expect(parseStandAm("2026-05-10")).toBe("2026-05-10");
	});

	it("dreht die deutsche Schreibweise auf ISO", () => {
		expect(parseStandAm("10.05.2026")).toBe("2026-05-10");
		expect(parseStandAm("1.5.2026")).toBe("2026-05-01");
	});

	it("ergänzt ein zweistelliges Jahr zum aktuellen Jahrhundert", () => {
		expect(parseStandAm("10.05.26")).toBe("2026-05-10");
	});
});

describe("readAnfangssaldo", () => {
	const note = (fm: string) => `---\n${fm}\n---\n\n# Konto\n`;

	it("liest beide Felder aus dem Frontmatter", () => {
		const result = readAnfangssaldo(
			note("anfangssaldo_eur: 443,72\nanfangssaldo_stand_am: 10.05.2026"),
		);
		expect(result.betrag?.toString()).toBe("443.72");
		expect(result.standAm).toBe("2026-05-10");
	});

	it("meldet null, solange die Felder auf null stehen", () => {
		const result = readAnfangssaldo(
			note("anfangssaldo_eur: null\nanfangssaldo_stand_am: null"),
		);
		expect(result.betrag).toBeNull();
		expect(result.standAm).toBeNull();
	});

	it("meldet null bei einer Notiz ohne Frontmatter", () => {
		expect(readAnfangssaldo("# Nur Text\n")).toEqual({
			betrag: null,
			standAm: null,
		});
	});

	it("meldet null statt zu werfen, wenn der Betrag Unsinn ist", () => {
		const result = readAnfangssaldo(note("anfangssaldo_eur: bald"));
		expect(result.betrag).toBeNull();
	});
});

describe("formatOpeningBalances", () => {
	it("schreibt ein Eröffnungs-Posting je Konto mit gefüllten Feldern", () => {
		const out = formatOpeningBalances(ctx, {
			"Konto 01 – Hauptkonto.md": "---\nanfangssaldo_eur: 443,72\nanfangssaldo_stand_am: 2026-05-10\n---\n",
		});

		expect(out).toContain("2026-05-10 * Eröffnungsbilanz Konto 01 – Hauptkonto");
		expect(out).toContain("    Aktiva:Bank:Sparkasse:Hauptkonto  443.72 EUR");
		expect(out).toContain("    Eigenkapital:Eroeffnungsbilanz  -443.72 EUR");
	});

	it("nennt das fehlende Feld beim Namen statt still zu schweigen", () => {
		const out = formatOpeningBalances(ctx, {
			"Konto 01 – Hauptkonto.md": "---\nanfangssaldo_eur: 443,72\n---\n",
		});

		expect(out).toContain("anfangssaldo_stand_am fehlt");
		expect(out).toContain("Konto 01 – Hauptkonto.md");
		expect(out).not.toContain("Eröffnungsbilanz Konto 01");
	});

	it("behandelt eine fehlende Konto-Notiz wie leere Felder", () => {
		const out = formatOpeningBalances(ctx, {});
		expect(out).toContain("anfangssaldo_eur + anfangssaldo_stand_am fehlt");
	});

	it("führt den Kopf mit dem Bootstrap-Hinweis", () => {
		const out = formatOpeningBalances(ctx, {});
		expect(out.startsWith("; Generated by finanzplan-importer\n")).toBe(true);
		expect(out).toContain("User-Edit-Schutz");
		expect(out.endsWith("\n")).toBe(true);
	});

	it("nennt im Kopf den eingestellten Konten-Ordner, nicht den fest verdrahteten", () => {
		const eigener = createImporterContext({
			konten: parseKontenConfig({ konten: [konto()] }),
			notesPrefix: "Geld",
			folders: { konten: "Konten" },
		});

		expect(formatOpeningBalances(eigener, {})).toContain("<Vault>/Konten/Konto 0X");
		expect(formatOpeningBalances(ctx, {})).toContain("<Vault>/10-Konten/Konto 0X");
	});
});
