import { describe, it, expect } from 'vitest';
import { parseOpeningBalances } from '../../src/aggregator/openingBalances';

describe('parseOpeningBalances (Slice-8 Burst-B)', () => {
  it('returns empty Map for comment-only file (heutiger Bootstrap-Pending-State)', () => {
    const text = `; Generated by 26-011-finanzplan-importer
; opening_balances.ledger — Anfangssalden pro Konto
;
; Konto 01: anfangssaldo_eur + anfangssaldo_stand_am fehlt — bitte in Konto 01 ....md setzen
`;
    const result = parseOpeningBalances(text);
    expect(result.size).toBe(0);
  });

  it('parses a CRLF opening-balances file (Windows importer) (H1)', () => {
    const text = [
      '2026-05-10 * Eröffnungsbilanz Konto 01',
      '    Aktiva:Bank:Sparkasse:Hauptkonto  443.72 EUR',
      '    Eigenkapital:Eroeffnungsbilanz  -443.72 EUR',
    ].join('\r\n');
    const result = parseOpeningBalances(text);
    expect(result.get('Aktiva:Bank:Sparkasse:Hauptkonto')?.amount).toBe(443.72);
    expect(result.get('Aktiva:Bank:Sparkasse:Hauptkonto')?.standAm).toBe('2026-05-10');
  });

  it('parses 4 postings with per-Konto standAm (Real-Bootstrap-Output)', () => {
    const text = `; Generated by 26-011-finanzplan-importer
; opening_balances.ledger — Anfangssalden pro Konto
;

2026-05-10 * Eröffnungsbilanz Konto 01 – Hauptkonto Sparkasse
    Aktiva:Bank:Sparkasse:Hauptkonto  443.72 EUR
    Eigenkapital:Eroeffnungsbilanz  -443.72 EUR

2026-05-10 * Eröffnungsbilanz Konto 02 – Familienpool Sparkasse
    Aktiva:Bank:Sparkasse:Familienpool  801.21 EUR
    Eigenkapital:Eroeffnungsbilanz  -801.21 EUR

2026-05-10 * Eröffnungsbilanz Konto 03 – Vermietung Sparkasse
    Aktiva:Bank:Sparkasse:Vermietung  2024.58 EUR
    Eigenkapital:Eroeffnungsbilanz  -2024.58 EUR

2026-05-10 * Eröffnungsbilanz Konto 04 – Visa Daily Sparkasse
    Aktiva:Bank:Sparkasse:Visa  -340.51 EUR
    Eigenkapital:Eroeffnungsbilanz  340.51 EUR
`;
    const result = parseOpeningBalances(text);
    expect(result.size).toBe(4);
    expect(result.get('Aktiva:Bank:Sparkasse:Hauptkonto')).toEqual({
      amount: 443.72,
      standAm: '2026-05-10',
    });
    expect(result.get('Aktiva:Bank:Sparkasse:Familienpool')).toEqual({
      amount: 801.21,
      standAm: '2026-05-10',
    });
    expect(result.get('Aktiva:Bank:Sparkasse:Vermietung')).toEqual({
      amount: 2024.58,
      standAm: '2026-05-10',
    });
    expect(result.get('Aktiva:Bank:Sparkasse:Visa')).toEqual({
      amount: -340.51,
      standAm: '2026-05-10',
    });
  });

  it('skips comments interleaved with postings', () => {
    const text = `; head
2026-05-10 * Eröffnungsbilanz Konto 01
    Aktiva:Bank:Sparkasse:Hauptkonto  100.00 EUR
    Eigenkapital:Eroeffnungsbilanz  -100.00 EUR
; Konto 02: anfangssaldo fehlt — bitte setzen
2026-05-10 * Eröffnungsbilanz Konto 03
    Aktiva:Bank:Sparkasse:Vermietung  500.00 EUR
    Eigenkapital:Eroeffnungsbilanz  -500.00 EUR
`;
    const result = parseOpeningBalances(text);
    expect(result.size).toBe(2);
    expect(result.get('Aktiva:Bank:Sparkasse:Hauptkonto')?.amount).toBe(100.0);
    expect(result.get('Aktiva:Bank:Sparkasse:Vermietung')?.amount).toBe(500.0);
  });

  it('returns empty Map for empty file', () => {
    expect(parseOpeningBalances('').size).toBe(0);
  });

  it('correctly captures per-Konto-standAm when dates differ', () => {
    const text = `2025-07-01 * Eröffnungsbilanz Konto 01
    Aktiva:Bank:Sparkasse:Hauptkonto  100.00 EUR
    Eigenkapital:Eroeffnungsbilanz  -100.00 EUR

2025-09-15 * Eröffnungsbilanz Konto 02
    Aktiva:Bank:Sparkasse:Familienpool  200.00 EUR
    Eigenkapital:Eroeffnungsbilanz  -200.00 EUR
`;
    const result = parseOpeningBalances(text);
    expect(result.get('Aktiva:Bank:Sparkasse:Hauptkonto')?.standAm).toBe(
      '2025-07-01'
    );
    expect(result.get('Aktiva:Bank:Sparkasse:Familienpool')?.standAm).toBe(
      '2025-09-15'
    );
  });

  it('ignores Eigenkapital-Gegenposting (only first Aktiva/Passiva captured)', () => {
    const text = `2026-05-10 * Eröffnungsbilanz Konto 01
    Aktiva:Bank:Sparkasse:Hauptkonto  100.00 EUR
    Eigenkapital:Eroeffnungsbilanz  -100.00 EUR
`;
    const result = parseOpeningBalances(text);
    expect(result.has('Eigenkapital:Eroeffnungsbilanz')).toBe(false);
    expect(result.has('Aktiva:Bank:Sparkasse:Hauptkonto')).toBe(true);
  });
});
