import { it, expect, describe } from 'vitest';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { parseLedger, parseLedgerWithDiagnostics } from '../../src/parser/ledger';

const __dirnameTest = dirname(fileURLToPath(import.meta.url));
const fixtureText = readFileSync(join(__dirnameTest, '../fixtures/sample-journal.ledger'), 'utf-8');

describe('parseLedger — fixture (7 transactions)', () => {
  it('parses exactly 7 transactions', () => {
    expect(parseLedger(fixtureText)).toHaveLength(7);
  });

  it('parses date and counterparty from header', () => {
    const txs = parseLedger(fixtureText);
    expect(txs[0].date).toBe('2025-05-07');
    expect(txs[0].counterparty).toBe('Baeckerei Konditorei Muster GmbH//FIL.01. MUSTERSTADT/DE');
  });

  it('parses two postings per transaction', () => {
    for (const tx of parseLedger(fixtureText)) {
      expect(tx.postings).toHaveLength(2);
    }
  });

  it('parses posting accounts and amounts (negative and positive)', () => {
    const tx = parseLedger(fixtureText)[0]; // Baeckerei
    expect(tx.postings[0].account).toBe('Aktiva:Bank:Sparkasse:Hauptkonto');
    expect(tx.postings[0].amountEur).toBe(-9.46);
    expect(tx.postings[1].account).toBe('Ausgaben:Lebensmittel:Baeckerei:Muster');
    expect(tx.postings[1].amountEur).toBe(9.46);
  });

  it('returns empty tags array when no tags present', () => {
    const tx = parseLedger(fixtureText)[0]; // Baeckerei — no tags
    expect(tx.tags).toEqual([]);
  });

  it('parses single tag', () => {
    const tx = parseLedger(fixtureText)[1]; // VW Leasing — :recurring:
    expect(tx.tags).toEqual(['recurring']);
  });

  it('parses multiple tags from one line', () => {
    const tx = parseLedger(fixtureText)[2]; // NOTPROVIDED — :tbc:unkategorisiert:
    expect(tx.tags).toContain('tbc');
    expect(tx.tags).toContain('unkategorisiert');
    expect(tx.tags).toHaveLength(2);
  });

  it('parses two tags on one line (:recurring:paypal-via:)', () => {
    const tx = parseLedger(fixtureText)[5]; // PayPal
    expect(tx.tags).toEqual(['recurring', 'paypal-via']);
  });

  it('parses tags case-insensitively — uppercase tags are not silently dropped (N2)', () => {
    const text = `2025-01-01 * Test\n    ; :Recurring:MixedCase:\n    Aktiva:Test  100.00 EUR\n    Ausgaben:Test  -100.00 EUR`;
    const tx = parseLedger(text)[0];
    expect(tx.tags).toEqual(['Recurring', 'MixedCase']);
  });

  it('parses quelle and verwendungszweck', () => {
    const tx = parseLedger(fixtureText)[0]; // Baeckerei
    expect(tx.quelle).toBe('20260506-0532013000-umsatz-camt52v8.CSV row 516');
    expect(tx.verwendungszweck).toBe('2025-05-06T07:11 Debitk.1 2099-12');
  });

  it('parses verwendungszweck with special characters (comma, slash, plus)', () => {
    const tx = parseLedger(fixtureText)[1]; // VW Leasing
    expect(tx.verwendungszweck).toContain('36,02');
    expect(tx.verwendungszweck).toContain('RATE05/25');
  });

  it('parses positive Aktiva income (AOK refund direction)', () => {
    const tx = parseLedger(fixtureText)[4]; // AOK
    expect(tx.postings[0].amountEur).toBe(1418.88);
    expect(tx.postings[1].amountEur).toBe(-1418.88);
    expect(tx.postings[1].account).toBe('Einnahmen:Krankengeld:KK_Muster');
  });

  it('ignores file-level comment header lines', () => {
    const text = `; Generated by importer\n; second comment\n\n2025-01-01 * Test\n    Aktiva:Test  100.00 EUR\n    Ausgaben:Test  -100.00 EUR`;
    expect(parseLedger(text)).toHaveLength(1);
  });

  it('handles multiple blank lines between transactions', () => {
    const text = `2025-01-01 * First\n    Aktiva:A  10.00 EUR\n    Ausgaben:A  -10.00 EUR\n\n\n2025-01-02 * Second\n    Aktiva:B  5.00 EUR\n    Ausgaben:B  -5.00 EUR`;
    const txs = parseLedger(text);
    expect(txs).toHaveLength(2);
    expect(txs[1].counterparty).toBe('Second');
  });

  it('returns null for quelle and verwendungszweck when not present', () => {
    const text = `2025-01-01 * Test\n    ; :recurring:\n    Aktiva:Test  100.00 EUR\n    Ausgaben:Test  -100.00 EUR`;
    const tx = parseLedger(text)[0];
    expect(tx.quelle).toBeNull();
    expect(tx.verwendungszweck).toBeNull();
  });
});

describe('parseLedger — line endings (H1)', () => {
  const lines = [
    '2025-01-01 * First',
    '    Aktiva:A  10.00 EUR',
    '    Ausgaben:A  -10.00 EUR',
    '',
    '2025-01-02 * Second',
    '    Aktiva:B  5.00 EUR',
    '    Ausgaben:B  -5.00 EUR',
  ];

  it('parses a CRLF journal (Windows importer) without silent data loss', () => {
    const crlf = lines.join('\r\n');
    const txs = parseLedger(crlf);
    expect(txs).toHaveLength(2);
    expect(txs[0].postings).toHaveLength(2);
    expect(txs[0].postings[0].amountEur).toBe(10.0);
    expect(txs[1].counterparty).toBe('Second');
  });

  it('parses a CR-only journal (classic-Mac line endings)', () => {
    const cr = lines.join('\r');
    expect(parseLedger(cr)).toHaveLength(2);
  });

  it('still parses plain LF journals identically', () => {
    const lf = lines.join('\n');
    expect(parseLedger(lf)).toHaveLength(2);
  });
});

describe('parseLedgerWithDiagnostics (H2/M1/M2)', () => {
  it('reports a posting line that failed to parse as skipped (partial loss)', () => {
    const text = [
      '2025-01-01 * Foo',
      '    Aktiva:Bank  -10.00 EUR',
      '    Ausgaben:X   10,00 EUR', // decimal comma → dropped
    ].join('\n');
    const { transactions, diagnostics } = parseLedgerWithDiagnostics(text);
    expect(transactions).toHaveLength(1); // tx still present (one posting parsed)
    expect(diagnostics.skippedLines.some(l => l.includes('10,00 EUR'))).toBe(true);
  });

  it('flags a transaction whose postings do not balance', () => {
    const text = [
      '2025-01-01 * Foo',
      '    Aktiva:Bank  -10.00 EUR',
      '    Ausgaben:X   10,00 EUR', // dropped → residual −10
    ].join('\n');
    const { diagnostics } = parseLedgerWithDiagnostics(text);
    expect(diagnostics.unbalanced).toHaveLength(1);
    expect(diagnostics.unbalanced[0].residualEur).toBeCloseTo(-10, 2);
    expect(diagnostics.unbalanced[0].counterparty).toBe('Foo');
  });

  it('accepts a single tab as account/amount separator (no loss)', () => {
    const text = '2025-01-01 * Foo\n\tAktiva:Bank\t-10.00 EUR\n\tAusgaben:X\t10.00 EUR';
    const { transactions, diagnostics } = parseLedgerWithDiagnostics(text);
    expect(transactions[0].postings).toHaveLength(2);
    expect(diagnostics.skippedLines).toHaveLength(0);
    expect(diagnostics.unbalanced).toHaveLength(0);
  });

  it('flags suspicious amounts with 3+ decimal places (thousand-dot risk, M2)', () => {
    const text = [
      '2025-01-01 * Foo',
      '    Aktiva:Bank  -1.234 EUR',
      '    Ausgaben:X    1.234 EUR',
    ].join('\n');
    const { diagnostics } = parseLedgerWithDiagnostics(text);
    expect(diagnostics.suspiciousAmounts.length).toBeGreaterThanOrEqual(1);
  });

  it('clean journal yields empty diagnostics', () => {
    const text = '2025-01-01 * Foo\n    Aktiva:Bank  -10.00 EUR\n    Ausgaben:X   10.00 EUR';
    const { diagnostics } = parseLedgerWithDiagnostics(text);
    expect(diagnostics.skippedLines).toHaveLength(0);
    expect(diagnostics.unbalanced).toHaveLength(0);
    expect(diagnostics.suspiciousAmounts).toHaveLength(0);
  });
});
