/**
 * Journal- und Kontenplan-Ausgabe im hledger-Format.
 *
 * Port der Journal-Teile von `output/ledger.py`. Die Eröffnungsbilanz
 * (`opening_balances.ledger`) hängt an den Konto-Notizen statt an den CSVs und
 * kommt deshalb erst mit E3 — sie bleibt bis dahin unverändert liegen, was
 * korrekt ist: ein CSV-Import ändert keinen Anfangssaldo.
 */

import type { ImporterContext } from "../config/context";
import type { MoneyValue } from "../money";
import {
	categorize,
	postingAccount,
	type CategorizationResult,
	type CategorizeInput,
} from "./categorize";
import type { CategorizerRules } from "./rules";
import type { BankTransaction } from "./transaction";

/**
 * Durchlaufkonto für Umbuchungen zwischen eigenen Konten.
 *
 * Bewusst **nicht** unter `Aktiva:` — es ist kein Vermögen, sondern ein
 * Durchlaufposten, und stand als `Aktiva:Umbuchung` mit über 8.000 € in der
 * Kontostandsübersicht und verfälschte deren Gesamtsumme.
 *
 * Es geht auch nicht zwingend auf null auf: decken zwei CSVs unterschiedliche
 * Zeiträume ab, fehlt für die Randbuchungen die Gegenseite. Das ist eine
 * Eigenschaft der Datenlage, kein Rechenfehler.
 */
export const CLEARING_ACCOUNT = "Verrechnung:Umbuchung";

const WHITESPACE_RUN = /\s+/g;

/** Eine Buchung mit ihrem Buchungskonto und ihrer Kategorisierung. */
export interface CategorizedTx {
	tx: BankTransaction;
	posting: string;
	result: CategorizationResult;
}

/** `-39.95 EUR` — Punkt-Notation, wie hledger sie erwartet. */
export function fmtEur(amount: MoneyValue): string {
	return `${amount.toFixed(2)} EUR`;
}

export function formatTransaction(
	tx: BankTransaction,
	postingAcct: string,
	gegenAccount: string,
	tags: readonly string[],
): string {
	const lines = [`${tx.buchungstag} * ${description(tx)}`];
	const vz = flat(tx.verwendungszweck);
	if (vz !== "") {
		lines.push(`    ; verwendungszweck: ${vz}`);
	}
	lines.push(`    ; quelle: ${tx.quelle} row ${tx.rawRowIdx}`);
	if (tags.length > 0) {
		// Alle Tags stehen auf einer Zeile zwischen Doppelpunkten — das Format,
		// das der Journal-Parser des Plugins liest.
		lines.push(`    ; :${tags.join(":")}:`);
	}
	lines.push(`    ${postingAcct}  ${fmtEur(tx.betrag)}`);
	lines.push(`    ${gegenAccount}  ${fmtEur(tx.betrag.negated())}`);
	lines.push("");
	return lines.join("\n");
}

/** Sortiert nach Datum, Quelldatei und Zeilennummer und formatiert. */
export function formatJournal(categorized: readonly CategorizedTx[]): string {
	const items = [...categorized].sort(
		(a, b) =>
			compare(a.tx.buchungstag, b.tx.buchungstag) ||
			compare(a.tx.quelle, b.tx.quelle) ||
			a.tx.rawRowIdx - b.tx.rawRowIdx,
	);
	const parts = [
		"; Generated by finanzplan-importer",
		"; journal.ledger — alle Buchungen aus den 4 Sparkasse-CSVs",
		"",
	];
	for (const item of items) {
		parts.push(
			formatTransaction(
				item.tx,
				item.posting,
				item.result.gegenAccount,
				item.result.tags,
			),
		);
	}
	return parts.join("\n");
}

/**
 * Konten, die hledger kennen soll.
 *
 * Der Kontenplan aus der Foundation, plus jedes Konto, das eine Regel oder ein
 * Sonderfall erzeugen kann. Ohne `account`-Direktive meldet hledger im
 * strikten Modus ein unbekanntes Konto.
 */
const STATIC_ACCOUNTS = [
	"Aktiva:Bank:Sparkasse:Hauptkonto",
	"Aktiva:Bank:Sparkasse:Familienpool",
	"Aktiva:Bank:Sparkasse:Vermietung",
	"Aktiva:Bank:Sparkasse:Visa",
	"Aktiva:Bank:Sparkasse:Bauspar:Wuestenrot",
	"Aktiva:Bank:Sparkasse:Bauspar:LBS_Sued",
	"Aktiva:Bargeld",
	"Aktiva:Sonstige_Selbst-Bewegung",
	"Passiva:Leasing:VW",
	"Passiva:Hypothek:StSpkMusterstadt",
	"Passiva:Bauspar:Wuestenrot",
	"Passiva:Bauspar:LBS_Sued",
	"Verrechnung:Umbuchung",
	"Eigenkapital:Eroeffnungsbilanz",
	"Einnahmen:Krankengeld:KK_Muster",
	"Einnahmen:Familie:Otto_Muster",
	"Einnahmen:Familie:Mia_Muster",
	"Einnahmen:Mieteinnahmen:Mieter_Erika",
	"Einnahmen:Mieteinnahmen:Mieter_Bruno",
	"Einnahmen:Erstattung:LV_1871",
	"Einnahmen:Refund:Online",
	"Einnahmen:Habenzinsen",
	"Einnahmen:Sonstiges",
];

/** Konten, die `categorize` unabhängig von den Vault-Regeln erzeugen kann. */
const CATEGORIZER_ACCOUNTS = [
	"Ausgaben:Bankgebuehren:Entgelt",
	"Ausgaben:Bankgebuehren:Soll_Zinsen",
	"Ausgaben:Bankgebuehren:GA_Gebuehr",
	"Ausgaben:Bankgebuehren:FX_Aufschlag",
	"Ausgaben:Versicherung:Krankenversicherung:KK_Muster_Beitrag",
	"Ausgaben:Privat_Transfers:Partnerin:Erika",
	"Ausgaben:Unkategorisiert:PayPal",
	"Aktiva:Bargeld",
];

export function formatAccounts(
	ctx: ImporterContext,
	rules: CategorizerRules,
	signRuleAccounts: readonly string[] = [],
): string {
	const accounts = new Set<string>([
		...STATIC_ACCOUNTS,
		...CATEGORIZER_ACCOUNTS,
		...signRuleAccounts,
		// Die konfigurierten Bankkonten selbst — sonst fehlt genau das Konto,
		// das der Nutzer gerade neu angelegt hat.
		...ctx.activeKonten.map((k) => k.ledgerAccount),
		...rules.counterparty.map((r) => r.ledgerAccount),
		...rules.paypal.map((r) => r.ledgerAccount),
	]);

	const lines = [
		"; Generated by finanzplan-importer",
		"; accounts.ledger — Konten-Plan (Foundation §2)",
		"",
		...[...accounts].sort().map((a) => `account ${a}`),
		"",
	];
	return lines.join("\n");
}

/**
 * Bucht Umbuchungen zwischen eigenen Konten über das Verrechnungskonto.
 *
 * Eine Umbuchung steht in **beiden** Kontoauszügen: einmal als Abgang beim
 * Quellkonto, einmal als Eingang beim Zielkonto. Wer aus jeder Zeile die
 * vollständige Transaktion samt Gegenseite bucht, bewegt beide Konten um den
 * doppelten Betrag.
 *
 * Ein Paarabgleich über Datum, Betrag und Kontenpaar scheitert an der Praxis:
 * die Kreditkartenabrechnung steht im Kartenauszug am 02., im Girokontoauszug
 * am 05. Ein Toleranzfenster wiederum verschmilzt zwei echte Umbuchungen
 * gleichen Betrags innerhalb der Frist.
 *
 * Deshalb strukturell: **jede Bankzeile bucht nur ihr eigenes Konto**, die
 * Gegenseite läuft übers Verrechnungskonto. Beide Seiten treffen sich dort und
 * heben sich auf. Kein Abgleich, keine Datumsannahme, und jede Bankzeile bleibt
 * einzeln nachvollziehbar.
 *
 * Nur wenn das Gegenkonto **selbst eine CSV liefert**, kommt die zweite Sicht
 * überhaupt. Sonst muss direkt aufs Zielkonto gebucht werden — andernfalls
 * bekäme es seine Bewegung nie und im Durchlaufkonto bliebe der Betrag liegen.
 */
export function routeSelfTransfersViaClearing(
	categorized: readonly CategorizedTx[],
	importedAccounts: ReadonlySet<string>,
): CategorizedTx[] {
	return categorized.map((item) => {
		const isSelfTransfer = item.result.tags.includes("self-transfer");
		if (
			isSelfTransfer &&
			importedAccounts.has(item.result.gegenAccount) &&
			item.result.gegenAccount !== CLEARING_ACCOUNT
		) {
			return {
				...item,
				result: { ...item.result, gegenAccount: CLEARING_ACCOUNT },
			};
		}
		return item;
	});
}

/** Buchungen kategorisieren und Umbuchungen übers Verrechnungskonto leiten. */
export function categorizeAll(
	transactions: readonly BankTransaction[],
	input: CategorizeInput,
): CategorizedTx[] {
	const categorized = transactions.map((tx) => ({
		tx,
		posting: postingAccount(tx, input.ctx),
		result: categorize(tx, input),
	}));
	return routeSelfTransfersViaClearing(
		categorized,
		input.ctx.importedLedgerAccounts,
	);
}

function description(tx: BankTransaction): string {
	const raw =
		tx.beguenstigter.trim() || tx.buchungstext.trim() || "(unbekannt)";
	return flat(raw);
}

/** Zeilenumbrüche und Mehrfach-Leerzeichen zu einem Leerzeichen. */
function flat(value: string): string {
	return value.replace(WHITESPACE_RUN, " ").trim();
}

function compare(a: string, b: string): number {
	return a < b ? -1 : a > b ? 1 : 0;
}
