/**
 * `opening_balances.ledger` — die Eröffnungsbilanz.
 *
 * Der Importer kennt nur, was in den CSVs steht; der Kontostand davor kommt aus
 * dem Online-Banking und wird von Hand in die Konto-Notiz eingetragen. Genau
 * deshalb sind `anfangssaldo_eur` und `anfangssaldo_stand_am` die einzigen
 * Felder, die der Importer **nie** schreibt — und diese Datei ist die Stelle,
 * an der er sie liest.
 *
 * Portiert aus `output/ledger.py` (§ opening_balances). Die Locale-Toleranz ist
 * kein Komfort, sondern notwendig: Obsidians Eigenschaften-Editor schreibt in
 * deutscher Locale `443,72` und `10.05.2026`, YAML liest das als Zeichenkette,
 * und ein naiver Parser macht daraus stillschweigend Unsinn.
 */

import type { ImporterContext } from "../config/context";
import type { IsoDate } from "../dates";
import { Money, type MoneyValue } from "../money";
import { fmtEur } from "./journal";
import { readFrontmatter } from "../notes/frontmatter";

/** Gegenkonto jeder Eröffnungsbuchung. */
export const EIGENKAPITAL_ACCOUNT = "Eigenkapital:Eroeffnungsbilanz";

export interface Anfangssaldo {
	betrag: MoneyValue | null;
	standAm: IsoDate | null;
}

/**
 * `"443,72"` → 443.72. Nimmt deutsche wie englische Schreibweise.
 *
 * Enthält der Wert ein Komma, ist es der Dezimaltrenner und etwaige Punkte sind
 * Tausendertrenner — die Kombination `1.234,56` ist sonst nicht auflösbar.
 */
export function parseAnfangssaldo(raw: string | number): MoneyValue {
	if (typeof raw === "number") {
		return new Money(raw);
	}
	let text = raw.trim();
	if (text.includes(",")) {
		if (text.includes(".")) {
			text = text.replace(/\./g, "");
		}
		text = text.replace(",", ".");
	}
	const value = new Money(text);
	if (!value.isFinite()) {
		throw new Error(`Anfangssaldo nicht lesbar: ${JSON.stringify(raw)}`);
	}
	return value;
}

/**
 * `"10.05.2026"` → `"2026-05-10"`. ISO bleibt ISO.
 *
 * Ein zweistelliges Jahr wird ins aktuelle Jahrhundert gehoben — `new Date(26,…)`
 * läge sonst im Jahr 1926.
 */
export function parseStandAm(raw: string): IsoDate {
	const text = raw.trim();
	const german = /^(\d{1,2})\.(\d{1,2})\.(\d{2}|\d{4})$/.exec(text);
	if (!german) {
		return text;
	}
	const [, day = "", month = "", year = ""] = german;
	const fullYear = year.length === 2 ? `20${year}` : year;
	return `${fullYear.padStart(4, "0")}-${month.padStart(2, "0")}-${day.padStart(2, "0")}`;
}

/**
 * Liest beide Felder aus einer Konto-Notiz.
 *
 * Ein unlesbarer Wert wird zu `null`, nicht zu einem Fehler: die Datei entsteht
 * bei jedem Import, und ein Tippfehler in einem von Hand gepflegten Feld darf
 * den Import nicht anhalten — er soll in der erzeugten Datei als fehlend
 * auftauchen und dort auffallen.
 */
export function readAnfangssaldo(noteText: string): Anfangssaldo {
	const { data } = readFrontmatter(noteText);
	return {
		betrag: readBetrag(data.anfangssaldo_eur),
		standAm: readStandAm(data.anfangssaldo_stand_am),
	};
}

/**
 * Baut die Datei aus den Konto-Notizen.
 *
 * `notes` bildet Dateinamen (mit `.md`) auf ihren Inhalt ab; was fehlt, gilt als
 * noch nicht ausgefüllt. Der Kern liest selbst keine Dateien.
 */
export function formatOpeningBalances(
	ctx: ImporterContext,
	notes: Readonly<Record<string, string>>,
): string {
	const lines = [
		"; Generated by finanzplan-importer",
		"; opening_balances.ledger — Anfangssalden pro Konto",
		";",
		"; Quelle: Konto-Note Frontmatter `anfangssaldo_eur` + `anfangssaldo_stand_am`.",
		"; Bootstrap: Werte aus Online-Banking ziehen und in der jeweiligen Konto-Note",
		`; unter <Vault>/${ctx.folders.konten}/Konto 0X – ....md setzen. Importer überschreibt diese`,
		"; Felder bei Re-Run NICHT (User-Edit-Schutz).",
		"",
	];

	for (const spec of ctx.activeKonten) {
		const filename = ctx.ibanToFilename.get(spec.iban) ?? spec.iban;
		const noteText = notes[`${filename}.md`];
		const { betrag, standAm } =
			noteText === undefined
				? { betrag: null, standAm: null }
				: readAnfangssaldo(noteText);

		if (betrag !== null && standAm !== null) {
			lines.push(
				`${standAm} * Eröffnungsbilanz ${filename}`,
				`    ${spec.ledgerAccount}  ${fmtEur(betrag)}`,
				`    ${EIGENKAPITAL_ACCOUNT}  ${fmtEur(betrag.negated())}`,
				"",
			);
			continue;
		}

		const missing: string[] = [];
		if (betrag === null) {
			missing.push("anfangssaldo_eur");
		}
		if (standAm === null) {
			missing.push("anfangssaldo_stand_am");
		}
		lines.push(
			`; ${filename}: ${missing.join(" + ")} fehlt — ` +
				`bitte in ${filename}.md Frontmatter setzen`,
		);
	}

	if (lines.at(-1) !== "") {
		lines.push("");
	}
	return lines.join("\n");
}

function readBetrag(raw: unknown): MoneyValue | null {
	if (!isFilled(raw)) {
		return null;
	}
	try {
		return parseAnfangssaldo(raw as string);
	} catch {
		return null;
	}
}

function readStandAm(raw: unknown): IsoDate | null {
	return isFilled(raw) ? parseStandAm(String(raw)) : null;
}

/** `null`/leer im YAML heißt „noch nicht eingetragen", nicht „Wert null". */
function isFilled(raw: unknown): boolean {
	if (typeof raw !== "string" && typeof raw !== "number") {
		return false;
	}
	const text = String(raw).trim();
	return text !== "" && text !== "null" && text !== "~";
}
